name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - name: Profile Readme Development Stats
        uses: anmol098/waka-readme-stats@V3
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_SHORT_INFO: false
          SHOW_LOC_CHART: false
          COMMIT_BY_ME: true
          SHOW_COMMIT: false
          SHOW_PROFILE_VIEWS: false
          UPDATED_DATE_FORMAT: "%m/%d/%Y %H:%M"
